"""Initial migration with schemas

Revision ID: 04783c7a8f98
Revises: 
Create Date: 2026-07-23 13:50:43.770000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04783c7a8f98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Creating schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS bronze;")
    op.execute("CREATE SCHEMA IF NOT EXISTS silver;")
    op.execute("CREATE SCHEMA IF NOT EXISTS gold;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_ad_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_table('bronze_extraction_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('general_search_id', sa.Integer(), nullable=False),
    sa.Column('first_image_src', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_table('dim_products',
    sa.Column('baseline_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('cpu_brand', sa.String(), nullable=False),
    sa.Column('cpu_model', sa.String(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('specs_summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('baseline_id'),
    schema='gold'
    )
    op.create_table('ft_gold_arbitrage_opportunities',
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('baseline_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('first_image_src', sa.String(), nullable=True),
    sa.Column('item_condition', sa.String(), nullable=False),
    sa.Column('specs_summary', sa.String(), nullable=False),
    sa.Column('is_urgent_sale', sa.Boolean(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('market_median_price', sa.Float(), nullable=False),
    sa.Column('potential_profit', sa.Float(), nullable=False),
    sa.Column('profit_margin_pct', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ad_id'),
    schema='gold'
    )
    op.create_table('ft_gold_market_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseline_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cpu_brand', sa.String(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('active_ads_count', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('last_recalculated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id'),
    schema='gold'
    )
    op.create_table('ft_gold_market_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('median_market_price', sa.Float(), nullable=False),
    sa.Column('total_volume_available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_table('ft_gold_price_drop_alerts',
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('initial_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('price_change_pct', sa.Float(), nullable=False),
    sa.Column('days_on_market', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ad_id'),
    schema='gold'
    )
    op.create_table('silver_clean_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('item_condition', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('storage_gb', sa.Float(), nullable=True),
    sa.Column('cpu_brand', sa.String(), nullable=False),
    sa.Column('cpu_model', sa.String(), nullable=False),
    sa.Column('gpu_brand', sa.String(), nullable=False),
    sa.Column('screen_size_pol', sa.Float(), nullable=True),
    sa.Column('for_donation', sa.Boolean(), nullable=False),
    sa.Column('accept_trades', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('first_image_src', sa.String(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('baseline_id', sa.String(), nullable=False),
    sa.Column('needs_repair', sa.Boolean(), nullable=False),
    sa.Column('urgent_sale', sa.Boolean(), nullable=False),
    sa.Column('item_condition_indicator', sa.Integer(), nullable=False),
    sa.Column('has_accessories', sa.Boolean(), nullable=False),
    sa.Column('has_bluetooth', sa.Boolean(), nullable=False),
    sa.Column('has_cables', sa.Boolean(), nullable=False),
    sa.Column('has_hdmi', sa.Boolean(), nullable=False),
    sa.Column('has_ssd', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silver_clean_ads', schema='silver')
    op.drop_table('ft_gold_price_drop_alerts', schema='gold')
    op.drop_table('ft_gold_market_trends', schema='gold')
    op.drop_table('ft_gold_market_baselines', schema='gold')
    op.drop_table('ft_gold_arbitrage_opportunities', schema='gold')
    op.drop_table('dim_products', schema='gold')
    op.drop_table('bronze_extraction_data', schema='bronze')
    op.drop_table('bronze_ad_links', schema='bronze')
    # Removing schemas
    op.execute("DROP SCHEMA IF EXISTS gold CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS silver CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS bronze CASCADE;")
    # ### end Alembic commands ###
